name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment: PROD
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Pack project
      run: dotnet pack ./src/Html2Pdf.Lib.csproj -c Release --no-build --output ./artifacts

    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}      

#  publish:
#    environment: PROD
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Pack project
#        run: dotnet pack ./src/Html2Pdf.Lib.csproj -c Release --no-build --output ./artifacts
#
#      - name: Publish to NuGet
#        run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}